[package]
name = "spark_xxhash64_pyarrow"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "spark_xxhash64_pyarrow"
crate-type = ["cdylib"]

[dependencies]
spark-xxhash64-core = { path = "../spark-xxhash64-core" }
arrow = { version = "56", default-features = false, features = ["pyarrow"] }
pyo3 = { version = "=0.25.1", features = ["extension-module", "abi3-py39"] }
