"""Ground-truth vectors generated by compiling the real xxHash C reference
(Cyan4973/xxHash) with gcc and calling XXH64() directly -- see the
'Verification' section of the README for how these were produced. These
pin down every branch of the algorithm (short-input path, 32-byte block
loop, 8/4/1-byte remainders, negative seeds).
"""
import struct

from pyspark_xxhash64.core import xxh64_unsigned, MASK64


def u(signed: int) -> int:
    return signed & MASK64


def test_short_strings():
    assert xxh64_unsigned(b"", 0) == u(17241709254077376921)
    assert xxh64_unsigned(b"", 42) == u(11002672306508523268)
    assert xxh64_unsigned(b"a", 0) == u(15154266338359012955)
    assert xxh64_unsigned(b"abc", 0) == u(4952883123889572249)
    assert xxh64_unsigned(b"Spark", 0) == u(3483463169660459407)
    assert xxh64_unsigned(b"Spark", 42) == u(14152276016018486711)
    assert xxh64_unsigned(b"hello world", 42) == u(7620854247404556961)
    assert xxh64_unsigned(b"hello", 42) == u(-4367754540140381902)


def test_packed_ints():
    assert xxh64_unsigned(struct.pack("<i", 42), 42) == 18059084824599107352
    assert xxh64_unsigned(struct.pack("<i", -1), 42) == 2017008487422258757
    assert xxh64_unsigned(struct.pack("<i", 0), 42) == 3614696996920510707
    assert xxh64_unsigned(struct.pack("<q", 42), 42) == 11570577783400690398
    assert xxh64_unsigned(struct.pack("<q", -123456789012345), 42) == 15571690516402473978
    assert xxh64_unsigned(struct.pack("<q", 0), 42) == 13194218611613725804


def test_all_length_branches():
    buf = bytes(((i * 7 + 3) & 0xFF) for i in range(200))
    expected = {
        1: 5580451351978070747, 2: 6215351631807928157, 3: 13784906890744036254,
        4: 13597847860507385357, 5: 4205073633291343950, 6: 800032465557652724,
        7: 11305614215851539613, 8: 11522592252713084489, 9: 13287529681554990940,
        15: 8635722437317765341, 16: 9750327676900920104, 17: 8368118500704493432,
        31: 1201205969444977207, 32: 2535104866970686655, 33: 11315364974574533407,
        63: 373700720884083039, 64: 16078328808361457376, 65: 9796723603750889560,
        100: 9065759142320022946, 127: 9521134885471930803, 128: 939261268115044521,
        129: 15099910935766920641, 199: 292647177061165570,
    }
    for length, exp in expected.items():
        assert xxh64_unsigned(buf[:length], 42) == u(exp), length


def test_negative_and_large_seeds():
    expected = {
        -9223372036854775808: 16562101180679649828,
        -2147483649: 11247306118225086087,
        0: 2794345569481354659,
        2147483648: 14115809284154772049,
        9223372036854775807: 6473767341374282364,
    }
    for seed, exp in expected.items():
        assert xxh64_unsigned(b"hello", seed) == u(exp), seed
